### ISSUE TITLE
Create Coupon Referral Program demo

### ISSUE THREAD

**Issue by circuitfive** [cloudsponge/better-sharing-wp#24]
This should be in a multidev branch of the demo sandbox in Pantheon.

Related to #11

https://woocommerce.com/products/coupon-referral-program/

**Comment by dimitarangelkov** [comment]
This is the demo URL
https://coupon-ref-better-sharing-demo.pantheonsite.io/
https://coupon-ref-better-sharing-demo.pantheonsite.io/wp-adminn/

The add-on installation is still in progress. Will post an update when ready.

**Comment by dimitarangelkov** [comment]
@royboy789  I'll need your help to finalise the setup. Unfortunately I don't have the Coupon Referral Program extension source, so would appreciate if you can add it to the respective Pantheon MultiDev repo. @circuitfive  perhaps worth buying licenses for all 3rd party plugins/extensions, so they are fully functional? 

The other thing I've noticed is that the latest 1.1.0 plugin version is throwing an error when initialising the Coupon and Wishlists addons, so temporary commented the code below in `BetterSharingWP.php` in order to be able to run the plugin.
```

	$BWPAddOns_CouponReferral = new CouponReferralProgram();
	$BetterSharingWP->initAddOn( $BWPAddOns_CouponReferral );

	$BWPAddons_WooWishLists = new WooWishlists(); 
	$BetterSharingWP->initAddOn( $BWPAddons_WooWishLists );

```
